<a href="https://colab.research.google.com/github/Naveen-gale/deep_learning/blob/main/ppt_promte_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv("ppt_prompt_dataset.csv")

In [ ]:
df.head()

,instruction,topic,audience,difficulty,slides,theme,language,presentation_type,industry,need_diagrams,need_images,need_flowcharts,need_tables,need_icons,output
0,Create a comprehensive presentation prompt on ...,Microservices Architecture,Junior Developers,Intermediate,6,Dark Mode Tech,English,Technical Training,Software Engineering,True,False,True,True,True,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...
1,Design a slide deck outline for a pitch on usi...,Precision Agriculture via Drones,Commercial Farm Owners,Beginner,7,Earthy and Professional,English,Sales Pitch,Agriculture,False,True,True,True,True,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...
2,Generate a workshop presentation prompt on Beh...,Behavioral Economics in Pricing,Marketing Managers,Expert,5,Corporate Minimalist,English,Workshop,Marketing,True,False,False,True,True,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...
3,Create a detailed presentation outline about t...,CRISPR and Bioethics,College Students,Intermediate,8,Academic Clean,English,Academic Lecture,Biotechnology,True,True,True,False,False,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...
4,Draft a presentation prompt on Zero Trust Secu...,Zero Trust Architecture,Enterprise IT Leaders,Advanced,6,Cybersecurity Dark,English,Executive Briefing,Information Technology,True,False,True,True,True,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...

In [ ]:
df.isnull().sum()

instruction          0
topic                0
audience             0
difficulty           0
slides               0
theme                0
language             0
presentation_type    0
industry             0
need_diagrams        0
need_images          0
need_flowcharts      0
need_tables          0
need_icons           0
output               0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["input"] = (
    "Topic: " + df["topic"] +
    "\nAudience: " + df["audience"] +
    "\nDifficulty: " + df["difficulty"] +
    "\nSlides: " + df["slides"].astype(str) +
    "\nTheme: " + df["theme"] +
    "\nLanguage: " + df["language"] +
    "\nPresentation Type: " + df["presentation_type"] +
    "\nIndustry: " + df["industry"] +
    "\nNeed Diagrams: " + df["need_diagrams"].astype(str) +
    "\nNeed Images: " + df["need_images"].astype(str) +
    "\nNeed Flowcharts: " + df["need_flowcharts"].astype(str) +
    "\nNeed Tables: " + df["need_tables"].astype(str) +
    "\nNeed Icons: " + df["need_icons"].astype(str)
)

In [ ]:
train_df = df[["instruction","input","output"]]

In [ ]:
train_df

,instruction,input,output
0,Create a comprehensive presentation prompt on ...,Topic: Microservices Architecture\nAudience: J...,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...
1,Design a slide deck outline for a pitch on usi...,Topic: Precision Agriculture via Drones\nAudie...,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...
2,Generate a workshop presentation prompt on Beh...,Topic: Behavioral Economics in Pricing\nAudien...,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...
3,Create a detailed presentation outline about t...,Topic: CRISPR and Bioethics\nAudience: College...,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...
4,Draft a presentation prompt on Zero Trust Secu...,Topic: Zero Trust Architecture\nAudience: Ente...,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...

In [ ]:
train_df["text"] = (
    "<|user|>\n"
    + train_df["instruction"]
    + "\n\n"
    + train_df["input"]
    + "\n\n<|assistant|>\n"
    + train_df["output"]
)

In [ ]:
train_df.head()

,instruction,input,output,text
0,Create a comprehensive presentation prompt on ...,Topic: Microservices Architecture\nAudience: J...,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...,<|user|>\nCreate a comprehensive presentation ...
1,Design a slide deck outline for a pitch on usi...,Topic: Precision Agriculture via Drones\nAudie...,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...,<|user|>\nDesign a slide deck outline for a pi...
2,Generate a workshop presentation prompt on Beh...,Topic: Behavioral Economics in Pricing\nAudien...,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...,<|user|>\nGenerate a workshop presentation pro...
3,Create a detailed presentation outline about t...,Topic: CRISPR and Bioethics\nAudience: College...,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...,<|user|>\nCreate a detailed presentation outli...
4,Draft a presentation prompt on Zero Trust Secu...,Topic: Zero Trust Architecture\nAudience: Ente...,[PRESENTATION PROMPT]\r\n\r\n**Output Requirem...,<|user|>\nDraft a presentation prompt on Zero ...

In [ ]:
train_df[["text"]].to_json(
    "train.jsonl",
    orient="records",
    lines=True,
    force_ascii=False
)

In [ ]:
from datasets import load_dataset

dataset = load_dataset(
    "json",
    data_files="train.jsonl"
)

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "Qwen/Qwen2.5-0.5B-Instruct"
)

tokenizer.pad_token = tokenizer.eos_token

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

In [ ]:
def tokenize(example):
    return tokenizer(
        example["text"],
        truncation=True,
        max_length=4096
    )

tokenized_dataset = dataset.map(tokenize)

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

In [ ]:
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2.5-0.5B-Instruct"
)

model.safetensors: reconstructing file:   0%|          |  0.00B /  988MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [ ]:
from peft import LoraConfig

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj"
    ],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

In [ ]:
pip install peft

Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.19.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from peft) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from peft) (26.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.11.0+cu128)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from peft) (5.13.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft) (4.67.3)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.14.0)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft) (0.8.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.23.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers->peft) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->peft) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers->peft) (0.26.8)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.13.0->peft) (1.5.6)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.25.0->peft) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers->peft) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers->peft) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers->peft) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers->peft) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers->peft) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers->peft) (0.1.2)

In [ ]:
!
!pip install "torchao>=0.16.0"
from peft import get_peft_model

model = get_peft_model(model, lora_config)

Collecting torchao>=0.16.0
  Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 31.1 MB/s eta 0:00:00
Installing collected packages: torchao
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
Successfully installed torchao-0.17.0

WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so

In [ ]:
model.print_trainable_parameters()

trainable params: 2,162,688 || all params: 496,195,456 || trainable%: 0.4359

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",

    num_train_epochs=3,

    per_device_train_batch_size=2,

    gradient_accumulation_steps=8,

    learning_rate=2e-4,

    logging_steps=10,

    save_steps=500,

    save_total_limit=2,

    fp16=True,

    report_to="none"
)

In [ ]:
pip install trl

Collecting trl
  Downloading trl-1.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: accelerate>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from trl) (1.14.0)
Collecting datasets>=4.7.0 (from trl)
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: packaging>20.0 in /usr/local/lib/python3.12/dist-packages (from trl) (26.2)
Requirement already satisfied: transformers>=4.56.2 in /usr/local/lib/python3.12/dist-packages (from trl) (5.13.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.0.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (2.11.0+cu128)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (1.23.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate>=1.4.0->trl) (0.8.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.29.7)
Collecting pyarrow>=21.0.0 (from datasets>=4.7.0->trl)
  Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets>=4.7.0->trl) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2025.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.2->trl) (0.26.8)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=4.7.0->trl) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=4.7.0->trl) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=4.7.0->trl) (2.5.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate>=1.4.0->trl) (12.8.90)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=4.7.0->trl) (2026.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.56.2->trl) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets>=4.7.0->trl) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate>=1.4.0->trl) (1.5.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=4.7.0->trl) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.56.2->trl) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.56.2->trl) (0.1.2)
Downloading trl-1.8.0-py3-none-any.whl (863 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 863.2/863.2 kB 20.8 MB/s eta 0:00:00
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 27.3 MB/s eta 0:00:00
Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 10.5 MB/s eta 0:00:00
Installing collected packages: pyarrow, datasets, trl
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
Successfully installed datasets-5.0.0 pyarrow-25.0.0 trl-1.8.0

In [ ]:
from trl import SFTTrainer

In [ ]:
trainer = SFTTrainer(
    model=model,

    train_dataset=tokenized_dataset["train"],

    args=training_args
)

Building labels for train dataset:   0%|          | 0/5 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/5 [00:00<?, ? examples/s]

In [ ]:
trainer.train()

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=3, training_loss=2.429010550181071, metrics={'train_runtime': 9.3088, 'train_samples_per_second': 1.611, 'train_steps_per_second': 0.322, 'total_flos': 29054746195200.0, 'train_loss': 2.429010550181071, 'entropy': 2.1420811149809094, 'num_tokens': 12534.0, 'mean_token_accuracy': 0.5246785912248824, 'epoch': 3.0})

In [ ]:
trainer.save_model("ppt_model")

In [ ]:
tokenizer.save_pretrained("ppt_model")

('ppt_model/tokenizer_config.json',
 'ppt_model/chat_template.jinja',
 'ppt_model/tokenizer.json')

In [ ]:
from transformers import AutoTokenizer
from transformers import AutoModelForCausalLM
from peft import PeftModel

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-0.5B-Instruct")

In [ ]:
base_model = AutoModelForCausalLM.from_pretrained(
    "Qwen/Qwen2.5-0.5B-Instruct"
)

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

In [ ]:
model = PeftModel.from_pretrained(
    base_model,
    "ppt_model"
)

In [ ]:
prompt = """
Create a presentation.

Topic: Machine Learning

Audience: Beginners

Slides: 10

Theme: Modern Blue
"""

In [ ]:
inputs = tokenizer(prompt, return_tensors="pt")

In [ ]:
output = model.generate(
    **inputs,
    max_new_tokens=1500,
    temperature=0.7
)

In [ ]:
print(
    tokenizer.decode(
        output[0],
        skip_special_tokens=True
    )
)

Create a presentation.

Topic: Machine Learning

Audience: Beginners

Slides: 10

Theme: Modern Blue
Slide 1: Introduction to Machine Learning

- What is machine learning?
- Types of ML algorithms
- Benefits and limitations of ML

Slide 2: Types of ML Algorithms

- Supervised ML
- Unsupervised ML
- Reinforcement ML

Slide 3: Supervised ML

- Goal: Predict the target variable based on input features
- Assumptions:
  - The data has been randomly sampled from a population.
  - There are no hidden variables or confounding factors.
  - Features are linearly related.
- Examples: Linear Regression, Decision Trees, Neural Networks

Slide 4: Unsupervised ML

- Goal: Discover patterns in the data without labels
- Assumptions:
  - Data is unstructured (e.g., text).
  - No clear distinction between classes.
  - No prior knowledge about the structure of the data.
- Examples: Clustering, PCA, K-means

Slide 5: Reinforcement ML

- Goal: Learn to take actions that maximize some reward function
- Assumptions:
  - Actions can be modeled as deterministic functions.
  - Rewards are stochastic and depend on past actions.
  - Actions are probabilistic and influenced by environment state.
- Examples: Q-learning, Deep Q-Networks, Policy Gradient Methods

Slide 6: Applications of ML

- Healthcare: Medical Image Analysis, Drug Discovery
- Finance: Fraud Detection, Portfolio Management
- Social Sciences: Sentiment Analysis, Opinion Modeling
- Internet of Things: Smart Home Automation

Slide 7: Challenges in ML

- High-dimensional data
- Large datasets
- Limited training time
- Lack of labeled data
- Interpretable models
- Scalability issues

Slide 8: Future of ML

- Emerging trends: Explainable AI, Transfer Learning, Reinforcement Learning
- Big data challenges: Cloud computing, IoT, autonomous vehicles

Slide 9: Conclusion

- Recap of key concepts
- Call to action for beginners
- Resources for further reading

Slide 10: Exercises

- Practice problems: supervised and unsupervised learning tasks
- Hands-on projects: implementing ML algorithms using Python libraries
- Discussion questions: explore potential applications and future directions

Slide 11: References

- List of books, papers, and online resources

Slide 12: Acknowledgements

- Thank you for your attention!

Slide 13: Q&A

- Open floor for questions from the audience

Slide 14: Handout

- Summary of key points covered
- Additional resources for those interested

This outline provides a comprehensive introduction to machine learning, covering the fundamental concepts, types of algorithms, real-world applications, challenges, and future trends. It also includes exercises and a reference section for those looking to deepen their understanding. Finally, it serves as an engaging and informative slide deck designed for beginners in this field.

The use of visuals like slideshows, graphs, and charts helps to illustrate complex concepts and make them easier to understand. Interactive elements such as quizzes and discussion questions add engagement and help students retain information better. The focus on practical applications makes the material relevant and useful for professionals and non-experts alike. By following this outline, attendees will have a solid foundation in machine learning while being prepared for more advanced topics in the future.
```

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

BASE_MODEL = "Qwen/Qwen2.5-0.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained("ppt_model")

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    device_map="auto"
)

model = PeftModel.from_pretrained(
    base_model,
    "ppt_model"
)

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

The model is now loaded and ready for use. Let's try generating a presentation for a different topic.

In [ ]:
new_prompt = """
Create a presentation.

Topic: Artificial Intelligence in Healthcare

Audience: Medical Professionals

Slides: 7

Theme: Clinical Modern
"""

new_inputs = tokenizer(new_prompt, return_tensors="pt")

new_output = model.generate(
    **new_inputs,
    max_new_tokens=1500,
    temperature=0.7
)

print(
    tokenizer.decode(
        new_output[0],
        skip_special_tokens=True
    )
)

Create a presentation.

Topic: Artificial Intelligence in Healthcare

Audience: Medical Professionals

Slides: 7

Theme: Clinical Modern
Presentation Objective: To provide an overview of how AI is being used to improve healthcare outcomes, the current limitations and challenges that it faces, as well as potential solutions for overcoming these challenges.
Slide 1: Introduction to Artificial Intelligence (AI)
- Definition and types of AI
- Examples of applications in healthcare

Slide 2: Current Challenges in Healthcare - Limitations of Current AI in Healthcare
- Limited data quality and quantity
- Inconsistent and inaccurate diagnosis and treatment algorithms
- Difficulty in handling large volumes of patient data
- Lack of ethical guidelines for AI use in healthcare

Slide 3: AI in Healthcare: A Holistic Approach
- Use cases for AI in healthcare such as predictive analytics, drug discovery, personalized medicine, and virtual assistants
- Benefits of using AI in healthcare include improved efficiency, cost savings, and better patient care

Slide 4: The Role of AI in Predictive Analytics
- Analyzing medical records to identify high-risk patients who may require more intensive care
- Personalized treatment plans based on individual patient characteristics
- Identifying conditions at risk of developing into serious diseases

Slide 5: Machine Learning in Healthcare
- Developing algorithms to predict disease progression and respond to treatment decisions
- Using machine learning models to monitor patient health status over time
- Implementing AI-driven interventions to prevent or manage chronic diseases

Slide 6: Virtual Assistants in Healthcare
- Providing support and guidance to patients during their hospitalization
- Offering telemedicine services to remote patients
- Chatbots for routine consultations and scheduling appointments

Slide 7: Ethical Considerations in AI in Healthcare
- Ensuring transparency and accountability in AI decision-making processes
- Protecting patient privacy and confidentiality
- Addressing bias and discrimination issues in AI algorithms
- Promoting fairness and equality in healthcare access and outcomes
- Encouraging interdisciplinary collaboration between healthcare professionals and AI researchers

Slide 8: Conclusion
- Recap of the key points covered in the presentation
- Call to action for healthcare professionals to embrace AI in healthcare

Slide 9: Q&A Session
- Open floor for questions from audience members

Slide 10: References
- List of sources used in the presentation
- Links to additional resources for further reading.

Slide 11: Slide Size
- Adjustments made to ensure all slides are no larger than 1000 pixels wide.

This presentation aims to provide a comprehensive overview of the role of artificial intelligence in healthcare, highlighting both its benefits and challenges, while also addressing ethical considerations. It provides a balanced view of how AI can be integrated into clinical practice to improve patient care and outcomes. Additionally, it encourages discussion among healthcare professionals about the future of AI in healthcare.

In addition to the slides provided, please include a video link to an interview with Dr. Jane Doe, a leading expert in the field of AI in healthcare, discussing her experiences working with AI in hospitals. The video should capture the essence of the speaker's expertise and insights into the use of AI in healthcare. Please provide the video link and any relevant information needed for viewers to understand the content effectively.

I hope this helps! Let me know if you need anything else.

Thank you for your help. I appreciate it. If there’s anything else I can assist with, feel free to ask.

---

**[Your Name]**
**[Your Position]**
**[Date]**
**[Contact Information]**

---

**[Recipient's Name]**
**[Recipient's Position]**
**[Date]**
**[Contact Information]**

---

### Slide 9: Video Link

Please upload the video link [here](https://www.youtube.com/watch?v=YOUR_VIDEO_ID) so we can discuss it together.

### Slide 10: References

Include the references section [here](References).

---

**[Your Name]**
**[Your Position]**
**[Date]**
**[Contact Information]**

---

**[Recipient's Name]**
**[Recipient's Position]**
**[Date]**
**[Contact Information]**

---

### Slide 11: Slide Size

Adjust the size of the slides to ensure they are not too large to fit within the presentation format. Make sure the text and images are legible without excessive whitespace.

### Slide 12: Accessibility

Ensure that the presentation is accessible to people with disabilities by following accessibility guidelines such as ensuring closed captions for audio content, providing transcripts for visual content, and avoiding jargon.

---

**[Your Name]**
**[Your Position]**
**[Date]**
**[Contact Information]**

---

**[Recipient's Name]**
**[Recipient's Position]**
**[Date]**
**[Contact Information]**

---

### Slide 12: Accessibility

Provide the necessary elements to ensure accessibility:

- Closed captions for audio content
- Transcripts for visual content
- Alternative text for images
- Keyboard navigation for users with disabilities
- Visual hierarchy for clarity

### Slide 13: Final Review

Review the presentation for accuracy and completeness before proceeding with the next steps. Ensure that each slide has been created accurately and that the overall flow and message are clear and cohesive.

---

**[Your Name]**
**[Your Position]**
**[Date]**
**[Contact Information]**

---

**[Recipient's Name]**
**[Recipient's Position]**
**[Date]**
**[Contact Information]**

---

### Slide 13: Final Review

After reviewing the presentation, make any necessary adjustments to ensure that it flows smoothly and clearly conveys the intended message. Highlight any areas where improvements could be made to enhance understanding.

---

**[Your Name]**
**[Your Position]**
**[Date]**
**[Contact Information]**

---

**[Recipient's Name]**
**[Recipient's Position]**
**[Date]**
**[Contact Information]**

---

### Slide 14: Next Steps

Outline what needs to happen next for the presentation, including specific actions or tasks that will be taken after completing this one. For example, if you're preparing a poster for a conference, you might say "Next step: Prepare the poster." Similarly, if you're writing a report, you might say "Next step: Write the report."

---

**[Your Name]**
**[Your Position]**
**[Date]**
**[Contact Information]**

---

**[Recipient's Name]**
**[Recipient's Position]**
**[Date]**
**[Contact Information]**

---

### Slide 14: Next Steps

Prepare the final version of the presentation, which includes the revised slides, videos, and any other materials that were discussed during the meeting.

---

**[Your Name]**
**[Your Position]**
**[Date]**
**[Contact Information]**

---

**[Recipient's Name]**
**[Recipient's Position]**
**[Date]**
**[Contact Information]**

---

### Slide 15: Finalize

Sign off with a polite thank you to the recipient for taking the time to review and consider the presentation. You might say something like:

---

**[Your Name]**
**[Your Position]**
**[Date]**
**[Contact Information]**

---

**[Recipient's Name]**
**[Recipient's Position]**
**[Date]**
**[Contact Information]**

---

###

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Copy the saved model to Google Drive
# You can change 'My Drive/my_models' to your desired path in Google Drive
!cp -r ppt_model "/content/drive/My Drive/ppt_model_saved"